### ISSUE TITLE
Also check age of up2date packages

### ISSUE THREAD

**Issue by FrankyBoy** [jaleskovec/reqcheck#1]
Hi!

Would be cool to also check the age of the latest package compared to today. 

Easiest to describe a use case I guess. I've got a project here that was using Flask-Security (which was abandoned 3 years ago, and picked up with Flask-Security-Too). We were on the latest version on, so this and many other tools would say "everything is great". However obviously 3 years out of date security is _never_ great, and in general no releases in over a year have a high likelyhood to indicate the project is dead. 

Proposal: add "Package Age" column or similar showing how old "latest" from pypi actually is.

Thanks :)

**Comment by jaleskovec** [comment]
Added in version 0.1.8. Thanks for the feature request!

**Comment by FrankyBoy** [comment]
Wow what a fast response. Awesome! 

Thanks mate :)
