### ISSUE TITLE
Add limits to fail CI builds

### ISSUE THREAD

**Issue by FrankyBoy** [jaleskovec/reqcheck#2]
Would be great to have command line flags to specify 
* maximum versions behind
* maximum version age behind (days)
* maximum package age behind (days) (#1)

and if that value is exceeded the program returns with an error code so a CI build could be made to fail.

**Comment by jaleskovec** [comment]
Thanks for this really useful feature request! It's been added in 0.1.9. Usage information is in the readme: https://github.com/jaleskovec/reqcheck#usage
--max-versions-behind, --max-days-behind and --max-age have been added. The --max-age parameter will look at the age of the installed package version. If you're on the latest version, it has the effect of looking at the age of the package as a whole.
